# This is a basic workflow to help you get started with Actions

name: Daily Scraper

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Prevents using default GitHub bot credentials

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js

      - name: Commit and Push JSON
        env:
          INSPIRE_SCRAPER: ${{ secrets.INSPIRE_SCRAPER }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update prayer timings [skip ci]" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tan-ahmed/inspire-prayer-scraper.git main
